name: "Spack Build-Cache"
description: "Install via Spack, push buildcache to a mirror"
branding:
  icon: package
  color: purple

inputs:
  # which Spack environment to use (directory under your repo-packages)
  env-variant:
    description: "Spack environment variant (e.g. 'default')"
    required: true
  # path to spack environments
  env-path:
    description: "local path to Spack environments"
    required: false
    default: ".spack"
  # where to pull your Spack packages from
  repo-packages:
    description: "GitHub repo with your Spack package recipes"
    required: false
    default: "numpex/spack.numpex"
  repo-packages-path:
    description: "Path to your Spack packages repo"
    required: false
    default: "spack.numpex"    
  # mirror name in Spack
  mirror:
    description: "Name of the Spack buildcache mirror"
    required: true
    default: "numpex-buildcache"

  # pass in your GitHub token or other OCI password
  mirror-token:
    description: "Password/token to push to the mirror (e.g. secrets.GITHUB_TOKEN)"
    required: true

  base-image:
    description: "Base container image for buildcache metadata"
    required: false
    default: "ubuntu:24.04"

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Set up Spack
      uses: spack/setup-spack@v2.1.1
      with:
        buildcache: true
        path: _spack
        color: true

    - name: Checkout Spack packages repo
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repo-packages }}
        path: ${{ inputs.repo-packages-path }}
        fetch-depth: 1

    - name: Add custom Spack repo
      shell: bash
      run: |
        . _spack/share/spack/setup-env.sh
        spack repo add "${{ inputs.packages-path }}"

    - name: Install & Push buildcache
      shell: bash
      env:
        SPACK_MIRROR_TOKEN: ${{ inputs.mirror-token }}
      run: |
        . _spack/share/spack/setup-env.sh
        spack -e "${{ inputs.env-path }}/${{ inputs.env-variant }}" install --no-check-signature
        spack -e "${{ inputs.env-path }}/${{ inputs.env-variant }}" mirror set --push \
          --oci-username "${{ github.actor }}" \
          --oci-password "${SPACK_MIRROR_TOKEN}" \
          "${{ inputs.mirror }}"
        spack -e "${{ inputs.env-path }}/${{ inputs.env-variant }}" buildcache push \
          --base-image "${{ inputs.base-image }}" \
          --unsigned \
          --update-index "${{ inputs.mirror }}"