name: "Spack Build-Cache"
description: "Install via Spack, push buildcache to a mirror"
branding:
  icon: package
  color: purple

inputs:
  environment:
    description: "Path to use as the environment"
    required: true
    default: .spack/default

  spack-path:
    description: "Path to install Spack to"
    required: false
    default: spack

  token:
    description: "The GitHub token. This will be used to push to the build cache."
    required: false
    default: ${{ github.token }}

  spack-ref:
    description: "Version of Spack (git ref: develop, releases/v0.23, ...)"
    required: false
    default: develop

runs:
  using: composite
  steps:
    - name: Set up Spack
      uses: spack/setup-spack@v2.1.1
      with:
        path: ${{ inputs.spack-path }}
        ref: ${{ inputs.spack-ref }}

    - name: Configure Spack
      shell: bash
      run: |
        . "${{ inputs.spack-path }}/share/spack/setup-env.sh"
        spack bootstrap now

        spack \
          mirror add \
          --scope site \
          --unsigned \
          --oci-username ${{ github.repository_owner }} \
          --oci-password ${{ inputs.token }} \
          buildcache-numpex \
          oci://ghcr.io/${{ github.repository }}

        spack compiler find --scope site

        # Sane defaults
        spack config --scope site add config:install_tree:root:/opt/root
        spack config --scope site add config:install_tree:padded_length:128

        spack config blame

    - name: Install Spack environment
      shell: bash
      run: |
        . "${{ inputs.spack-path }}/share/spack/setup-env.sh"
        spack -e "${{ inputs.environment }}" install

    - name: Activate Spack environment
      shell: bash
      run: |
        . "${{ inputs.spack-path }}/share/spack/setup-env.sh"
        spack env activate "${{ inputs.environment }}" --sh > /tmp/spack-env
        while IFS= read -r line; do
          if [[ "$line" =~ ^export\ (.*)=(.*)\;$ ]]; then
            exporting="${BASH_REMATCH[1]}=${BASH_REMATCH[2]}"
            echo ":: exporting $exporting"
            echo "$exporting" >> "$GITHUB_ENV"
          fi
        done < /tmp/spack-env

    - name: Push to cache
      uses: gacts/run-and-post-run@v1
      with:
        post: |
          . "${{ inputs.spack-path }}/share/spack/setup-env.sh"
          spack -e "${{ inputs.environment }}" buildcache \
            push \
            --update-index \
            --with-build-dependencies \
            buildcache-numpex
