name: Test Spack Build-Cache Action

on:
  push:
  pull_request:

jobs:
  smoke:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Spack Build-Cache
        uses: ./
        with:
          environment: .spack/default

      - name: Check specs
        run: |
          spack spec

      - name: Check programs
        run: |
          which -a cmake
